spring:
  application:
    name: centralized-configuration-server
  profiles:
    active: local
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Christianrslv/config-spring-cloud
          search-paths: config/
server:
  port: 8888
management:
  security:
    enabled: false